name: ci

on:
  push:
    branches: [master, main, v1.x]
  pull_request:
    branches: [master, main, v1.x]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: axios-0.21.4-node-${{ matrix.node-version }}
          path: axios-0.21.4.tgz
          retention-days: 1
